[package]
name = "cw_format"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
cw_parser = { path = "../cw_parser" }

[dev-dependencies]
pretty_assertions = "1.4.1"
